### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [nightblade9/genetic-roguelike#2]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by nightblade9** [comment]
Hi, 

I haven't actually decided on a license yet. In the meantime, since it's open-source, you're free to study and learn from it, run it, etc. as much as you like.

The actual core of the engine is pretty straight-forward, nothing fancy. If you wanted to write it from scratch, you could easily do so.
